#ifndef INTERFACE_H_INCLUDED
#define INTERFACE_H_INCLUDED

#define FONT_SIZE 16
#define TEXT_HEIGHT 20
#define SCREEN_SCROLL_SIZE 11
#define HELD_DELAY 300

#define MAIN_SCREEN 0
#define MANAGED_FILE_SCREEN 1
#define SELECTION_SCREEN 2
#define SELECTION_CONFIRM_SCREEN 3
#define SELECTION_RENAME_SCREEN 4
#define FILE_MANAGE_SCREEN 5

void interface_init();
void main_interface();

#endif
